Repository identique/idnumbers, pull requests merged in 2023-01, with the labels that each got.

#114 Fix #51 - implement Ireland Personal Public Service Number
  README.md
  idnumbers/nationalid/IRL.py
  idnumbers/nationalid/test_IRL.py
  idnumbers/nationalid/util.py
Labels: enhancement, Europe Continent

#117 Fix #6 - implement Mexico CURP
  README.md
  idnumbers/nationalid/MEX.py
  idnumbers/nationalid/constant.py
  idnumbers/nationalid/test_MEX.py
Labels: enhancement, Americas Continent

#118 Fix #14 implement indonesia nationalID
  idnumbers/nationalid/IDN.py
  idnumbers/nationalid/constant_IDN.py
  idnumbers/nationalid/test_IDN.py
Labels: enhancement, Asia Continent

#120 Fix #36 - implement the Belgium National Register Number
  README.md
  idnumbers/nationalid/BEL.py
  idnumbers/nationalid/test_BEL.py
Labels: enhancement, Europe Continent

#121 Fix #45 implement France national id
  README.md
  idnumbers/nationalid/FRA.py
  idnumbers/nationalid/test_FRA.py
Labels: enhancement, Europe Continent

#123 Fix #43 - implement Switzerland AVH and UID
  README.md
  idnumbers/nationalid/CHE.py
  idnumbers/nationalid/CHL.py
  idnumbers/nationalid/test_CHE.py
  idnumbers/nationalid/util.py
Labels: enhancement, Europe Continent

#127 Fix #80 - use pdoc to generate the API doc and upload to ghpages
  .github/workflows/docs.yml
Labels: enhancement, infra

#128 Fix #44 - implement Finland HETU national id
  README.md
  idnumbers/nationalid/FIN.py
  idnumbers/nationalid/test_FIN.py
Labels: enhancement, Europe Continent

#133 Fix #131 - rename the functions and add more docs
  idnumbers/nationalid/CHE.py
  idnumbers/nationalid/DEU.py
  idnumbers/nationalid/IRL.py
  idnumbers/nationalid/KOR.py
  idnumbers/nationalid/LKA.py
  idnumbers/nationalid/SGP.py
  idnumbers/nationalid/THA.py
  idnumbers/nationalid/TWN.py
  idnumbers/nationalid/util.py
Labels: documentation, enhancement

#135 Fix #112 - copy labels from title
  .github/workflows/copy-labels-to-pr.yml
Labels: enhancement, infra

#136 Fix #70 implement Sweden personal identity number
  README.md
  idnumbers/nationalid/SWE.py
  idnumbers/nationalid/test_SWE.py
Labels: enhancement, Europe Continent

#141 Fix #52: implement FiscalCode of Italy
  README.md
  idnumbers/nationalid/ITA.py
  idnumbers/nationalid/PRT.py
  idnumbers/nationalid/test_ITA.py
  idnumbers/nationalid/util.py
Labels: enhancement, Europe Continent

#143 Fix #142: write more docs
  docs/apidoc.md
  idnumbers/__init__.py
  idnumbers/nationalid/__init__.py
Labels: documentation, enhancement

#144 Fix #61: add the Poland PESEL
  README.md
  idnumbers/nationalid/POL.py
  idnumbers/nationalid/test_POL.py
Labels: enhancement, Europe Continent

#145 Fix #72 implement Turkey national ID number
  idnumbers/nationalid/TUR.py
  idnumbers/nationalid/test_TUR.py
Labels: enhancement, Europe Continent

#146 Fix #81 update readme and change doc string of TUR
  README.md
  idnumbers/nationalid/TUR.py
Labels: enhancement, infra

#150 Fix #149: remove the big map and use a small list for IDN
  idnumbers/nationalid/IDN.py
  idnumbers/nationalid/constant_IDN.py
Labels: enhancement, Asia Continent

#153 Fix #129 - add more docstrings
  idnumbers/nationalid/ARE.py
  idnumbers/nationalid/AUS.py
  idnumbers/nationalid/BEL.py
  idnumbers/nationalid/BRA.py
  idnumbers/nationalid/CHE.py
  idnumbers/nationalid/CHL.py
  idnumbers/nationalid/CHN.py
  idnumbers/nationalid/DEU.py
  idnumbers/nationalid/ESP.py
  idnumbers/nationalid/FRA.py
  idnumbers/nationalid/IND.py
  idnumbers/nationalid/IRL.py
  idnumbers/nationalid/JPN.py
  idnumbers/nationalid/KOR.py
  idnumbers/nationalid/LKA.py
  idnumbers/nationalid/MEX.py
  idnumbers/nationalid/MYS.py
  idnumbers/nationalid/NLD.py
  idnumbers/nationalid/NOR.py
  idnumbers/nationalid/NZL.py
  idnumbers/nationalid/PRT.py
  idnumbers/nationalid/SGP.py
  idnumbers/nationalid/SWE.py
  idnumbers/nationalid/THA.py
  idnumbers/nationalid/TUR.py
  idnumbers/nationalid/TWN.py
  idnumbers/nationalid/UKR.py
  idnumbers/nationalid/VNM.py
  idnumbers/nationalid/ZAF.py
  idnumbers/nationalid/constant.py
  idnumbers/nationalid/test_CHN.py
  idnumbers/nationalid/test_KOR.py
  idnumbers/nationalid/test_THA.py
Labels: documentation, enhancement

#154 Fix #151 - move test-cases to tests package and ignore them
  setup.py
  tests/__init__.py
  tests/nationalid/__init__.py
  tests/nationalid/test_ARE.py
  tests/nationalid/test_ARG.py
  tests/nationalid/test_AUS.py
  tests/nationalid/test_BEL.py
  tests/nationalid/test_BRA.py
  tests/nationalid/test_CAN.py
  tests/nationalid/test_CHE.py
  tests/nationalid/test_CHL.py
  tests/nationalid/test_CHN.py
  tests/nationalid/test_DEU.py
  tests/nationalid/test_ESP.py
  tests/nationalid/test_FIN.py
  tests/nationalid/test_FRA.py
  tests/nationalid/test_GBR.py
  tests/nationalid/test_HKG.py
  tests/nationalid/test_IDN.py
  tests/nationalid/test_IND.py
  tests/nationalid/test_IRL.py
  tests/nationalid/test_ITA.py
  tests/nationalid/test_JPN.py
  tests/nationalid/test_KOR.py
  tests/nationalid/test_LKA.py
  tests/nationalid/test_MEX.py
  tests/nationalid/test_MYS.py
  tests/nationalid/test_NGA.py
  tests/nationalid/test_NLD.py
  tests/nationalid/test_NOR.py
  tests/nationalid/test_NZL.py
  tests/nationalid/test_PHL.py
  tests/nationalid/test_POL.py
  tests/nationalid/test_PRT.py
  tests/nationalid/test_SGP.py
  tests/nationalid/test_SWE.py
  tests/nationalid/test_THA.py
  tests/nationalid/test_TUR.py
  tests/nationalid/test_TWN.py
  tests/nationalid/test_UKR.py
  tests/nationalid/test_USA.py
  tests/nationalid/test_VNM.py
  tests/nationalid/test_ZAF.py
  tests/nationalid/test_ZWE.py
Labels: enhancement, infra, release

#157 Fix #152 - change it to 5 - Production/Stable
  setup.py
Labels: enhancement, infra, release

#159 Fix #158: details the README.md
  README.md
Labels: documentation, enhancement

#160 Fix #38 implement Bulgaria Uniform civil number
  idnumbers/nationalid/BGR.py
  idnumbers/nationalid/util.py
  tests/nationalid/test_BGR.py
Labels: enhancement, Europe Continent

#163 Fix #68 - implement JMBG for Slovenia
  idnumbers/nationalid/SVN.py
  tests/nationalid/test_SVN.py
Labels: enhancement, Europe Continent

#164 Fix #162 - use TW instead of Tw
  idnumbers/nationalid/TWN.py
Labels: bug

#166 Fix #165 - change the name from microdataxyz to identique
  LICENSE
  README.md
  RELEASE.md
  docs/apidoc.md
  docs/nationalid/METADATA.md
  setup.py
Labels: documentation, enhancement
